version: "3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb:final
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mariadbv:/var/lib/mysql
    networks:
      - main
    secrets:
      - wpdblogin
      - wpdbname
      - wpdbpassword
      - dbrootlogin
      - dbrootpassword

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress:final
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - wpv:/var/www/html
    networks:
      - main
    depends_on:
      - mariadb
    secrets:
      - wpdbhost
      - wpdblogin
      - wpdbname
      - wpdbpassword
      - wpcontributorpassword
      - wpcontributorlogin
      - wpcontributoremail
      - wpadminpassword
      - wpadminlogin
      - wpadminemail
      
  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    image: nginx:final
    ports:
      - "443:443"
    restart: always
    volumes:
      - wpv:/var/www/html
    networks:
      - main
    secrets:
      - nginx_cert
      - nginx_key
  
volumes:
  mariadbv:
    driver: local
    driver_opts:
      type: none
      device: /home/imehdid/data/db
      o: bind
  wpv:
    driver: local
    driver_opts:
      type: none
      device: /home/imehdid/data/wp
      o: bind

secrets:
  nginx_cert:
    file: ../secrets/nginx/nginx.crt
  nginx_key:
    file: ../secrets/nginx/nginx.key
  wpdbhost:
    file: ../secrets/wordpress/wpdbhost.txt
  wpdblogin:
    file: ../secrets/wordpress/wpdblogin.txt
  wpdbname:
    file: ../secrets/wordpress/wpdbname.txt
  wpdbpassword:
    file: ../secrets/wordpress/wpdbpassword.txt
  wpcontributorpassword:
    file: ../secrets/wordpress/wpcontributorpassword.txt
  wpcontributorlogin:
    file: ../secrets/wordpress/wpcontributorlogin.txt
  wpcontributoremail:
    file: ../secrets/wordpress/wpcontributoremail.txt
  wpadminpassword:
    file: ../secrets/wordpress/wpadminpassword.txt
  wpadminlogin:
    file: ../secrets/wordpress/wpadminlogin.txt
  wpadminemail:
    file: ../secrets/wordpress/wpadminemail.txt
  dbrootlogin:
    file: ../secrets/mariadb/dbrootlogin.txt
  dbrootpassword:
    file: ../secrets/mariadb/dbrootpassword.txt

networks:
  main:
    driver: bridge