version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx/
    image: nginx
    ports:
      - "443:80"
    restart: always
    networks:
      - main

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"