CREATE DATABASE IF NOT EXISTS $WPDBNAME;
CREATE USER '$WPDBLOGIN'@'%' IDENTIFIED BY '$WPDBPASSWORD';
GRANT ALL PRIVILEGES ON $WPDBNAME.* TO '$WPDBLOGIN'@'%';
ALTER USER '$DBROOTLOGIN'@'localhost' IDENTIFIED BY '$DBROOTPASSWORD';
FLUSH PRIVILEGES;